FROM datajoint/djlab:py3.8-debian

USER root
RUN apt-get update -y
RUN apt-get install git -y

USER anaconda

RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/element-behavior \
          /main/workflow-behavior

# Copy user's local fork of elements and workflow
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-behavior /main/element-behavior
COPY --chown=anaconda:anaconda ./workflow-behavior /main/workflow-behavior

# Install packages
RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-behavior
RUN pip install -e /main/workflow-behavior
RUN pip install -r /main/workflow-behavior/requirements_test.txt

WORKDIR /main/workflow-behavior

ENTRYPOINT ["tail", "-f", "/dev/null"]
