blank_issues_enabled: false
contact_links:
  - name: DataJoint Contribution Guideline
    url: https://docs.datajoint.com/about/contribute/
    about: Please make sure to review the DataJoint Contribution Guidelines