FROM datajoint/djbase:py3.9-debian-8eb1715

# ARG GITHUB_USERNAME=datajoint # tried moving to ENV
USER anaconda:anaconda

COPY ./docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

WORKDIR /main/workflow-deeplabcut

# Always get interface/djarchive
RUN pip install --no-deps "element-interface@git+https://github.com/datajoint/element-interface"
RUN pip install --no-deps "djarchive-client@git+https://github.com/datajoint/djarchive-client"

# Always move local to temp, if they exist - conditional install in setup.sh
COPY --chown=anaconda:anaconda . \
                               ../element-lab? \
                               ../element-animal? \
                               ../element-session? \
                               ../element-event? \
                               ../element-interface? \
                               ../element-deeplabcut? \
                               /main/ 

# Conditional install - local-all, local-dlc, or git
RUN ./setup.sh 

RUN rm -f ./dj_local_conf.json
RUN pip install -r ./requirements_test.txt
