FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-deeplabcut/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/element-deeplabcut \
          /main/workflow-deeplabcut

# Copy user's local fork of elements and workflow
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-deeplabcut /main/element-deeplabcut
COPY --chown=anaconda:anaconda ./workflow-deeplabcut /main/workflow-deeplabcut

# Install packages
RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-deeplabcut
RUN pip install -e /main/workflow-deeplabcut
RUN pip install -r /main/workflow-deeplabcut/requirements_test.txt

WORKDIR /main/workflow-deeplabcut

ENTRYPOINT ["tail", "-f", "/dev/null"]
